### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Marty19** [Cryptcollector/Argentum#1]
Hi 

I am getting the following error when trying to compile the new wallet on Linux (boost 1.61):

`  CXXLD    argentumd
libbitcoin_wallet.a(walletdb.o): In function `boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option::enum_type)':
/usr/local/include/boost/filesystem/operations.hpp:539: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[3]: *** [argentumd] Error 1
`

Any ideas?

Thanks

**Comment by Marty19** [comment]
Don't worry....had boost 1.54 install as well. Once I removed that it compiled fine.

**Comment by Cryptcollector** [comment]
AH! I think I'll go mad now LOL
